name: Sync to live blendedforschools.online

on:
  push:
    tags: [ live ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing repo/sync-dms.sh on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIVE_HOST }}
        username: ${{ secrets.LIVE_USERNAME }}
        port: ${{ secrets.LIVE_PORT }}
        password: ${{ secrets.LIVE_PASSWORD }}
        script: /home/bash/live.sh
